retain_objc_accessible: true
retain_public: true
schemes:
- GeekBrainsTestProject
targets:
- GeekBrainsTestProject
workspace: /Users/denismordvinov/Desktop/Geekbrains/GeekBrainsiOSCourse/GBHomeWork2/GeekBrainsTestProject.xcworkspace
