# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build main target"
  lane :build do
    # add actions here: https://docs.fastlane.tools/actions
    xcodebuild(
      project: "GeekBrainsTestProject.xcodeproj",
      scheme: "GeekBrainsTestProject",
      xcodeproj: "GeekBrainsTestProject.xcodeproj"
    )
  end

  desc "Test main target"
  lane :tests do
    run_tests(scheme: "GeekBrainsTestProject")
  end
end
